// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate():Promise<void>;

export function CancelPrompt():Promise<void>;

export function SendPrompt(arg1:string):Promise<void>;

export function SendPromptWithSession(arg1:string,arg2:string):Promise<void>;
