// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPrompt() {
  return window['go']['main']['App']['CancelPrompt']();
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}

export function SendPromptWithSession(arg1, arg2) {
  return window['go']['main']['App']['SendPromptWithSession'](arg1, arg2);
}
